// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type GetAPIPendingRequestsGetPendingRequestsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TwoHundredTextPlainRes *string
	// OK
	TwoHundredApplicationJSONDBDomainRegistrationReqModels []shared.DBDomainRegistrationReqModel
	// OK
	TwoHundredTextJSONDBDomainRegistrationReqModels []shared.DBDomainRegistrationReqModel
}

func (o *GetAPIPendingRequestsGetPendingRequestsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIPendingRequestsGetPendingRequestsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIPendingRequestsGetPendingRequestsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPIPendingRequestsGetPendingRequestsResponse) GetTwoHundredTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextPlainRes
}

func (o *GetAPIPendingRequestsGetPendingRequestsResponse) GetTwoHundredApplicationJSONDBDomainRegistrationReqModels() []shared.DBDomainRegistrationReqModel {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONDBDomainRegistrationReqModels
}

func (o *GetAPIPendingRequestsGetPendingRequestsResponse) GetTwoHundredTextJSONDBDomainRegistrationReqModels() []shared.DBDomainRegistrationReqModel {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextJSONDBDomainRegistrationReqModels
}
