// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type GetAPICAGetACMECADetailsRequest struct {
	CaID *string `queryParam:"style=form,explode=true,name=caID"`
}

func (o *GetAPICAGetACMECADetailsRequest) GetCaID() *string {
	if o == nil {
		return nil
	}
	return o.CaID
}

type GetAPICAGetACMECADetailsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ACMECAsModel *string
	// OK
	ACMECAsModel1 *shared.ACMECAsModel
}

func (o *GetAPICAGetACMECADetailsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPICAGetACMECADetailsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPICAGetACMECADetailsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPICAGetACMECADetailsResponse) GetACMECAsModel() *string {
	if o == nil {
		return nil
	}
	return o.ACMECAsModel
}

func (o *GetAPICAGetACMECADetailsResponse) GetACMECAsModel1() *shared.ACMECAsModel {
	if o == nil {
		return nil
	}
	return o.ACMECAsModel1
}
