// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPICAAmIAdminResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TwoHundredTextPlainRes *string
	// OK
	TwoHundredApplicationJSONBoolean *bool
	// OK
	TwoHundredTextJSONBoolean *bool
}

func (o *GetAPICAAmIAdminResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPICAAmIAdminResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPICAAmIAdminResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPICAAmIAdminResponse) GetTwoHundredTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextPlainRes
}

func (o *GetAPICAAmIAdminResponse) GetTwoHundredApplicationJSONBoolean() *bool {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONBoolean
}

func (o *GetAPICAAmIAdminResponse) GetTwoHundredTextJSONBoolean() *bool {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextJSONBoolean
}
