// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type GetAPICACheckOrderStatusRequest struct {
	OrderID *string `queryParam:"style=form,explode=true,name=orderID"`
}

func (o *GetAPICACheckOrderStatusRequest) GetOrderID() *string {
	if o == nil {
		return nil
	}
	return o.OrderID
}

type GetAPICACheckOrderStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	OrderStatusModel *string
	// OK
	OrderStatusModel1 *shared.OrderStatusModel
}

func (o *GetAPICACheckOrderStatusResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPICACheckOrderStatusResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPICACheckOrderStatusResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPICACheckOrderStatusResponse) GetOrderStatusModel() *string {
	if o == nil {
		return nil
	}
	return o.OrderStatusModel
}

func (o *GetAPICACheckOrderStatusResponse) GetOrderStatusModel1() *shared.OrderStatusModel {
	if o == nil {
		return nil
	}
	return o.OrderStatusModel1
}
