// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type GetAPICAGetCAIntegrationsRequest struct {
	CaID *string `queryParam:"style=form,explode=true,name=caID"`
}

func (o *GetAPICAGetCAIntegrationsRequest) GetCaID() *string {
	if o == nil {
		return nil
	}
	return o.CaID
}

type GetAPICAGetCAIntegrationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TwoHundredTextPlainRes *string
	// OK
	TwoHundredApplicationJSONDBCAIntegrationModels []shared.DBCAIntegrationModel
	// OK
	TwoHundredTextJSONDBCAIntegrationModels []shared.DBCAIntegrationModel
}

func (o *GetAPICAGetCAIntegrationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPICAGetCAIntegrationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPICAGetCAIntegrationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPICAGetCAIntegrationsResponse) GetTwoHundredTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextPlainRes
}

func (o *GetAPICAGetCAIntegrationsResponse) GetTwoHundredApplicationJSONDBCAIntegrationModels() []shared.DBCAIntegrationModel {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONDBCAIntegrationModels
}

func (o *GetAPICAGetCAIntegrationsResponse) GetTwoHundredTextJSONDBCAIntegrationModels() []shared.DBCAIntegrationModel {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextJSONDBCAIntegrationModels
}
