// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPICARotateSCEPPasswordRequest struct {
	CaID       *string `queryParam:"style=form,explode=true,name=caID"`
	TemplateID *string `queryParam:"style=form,explode=true,name=templateID"`
}

func (o *GetAPICARotateSCEPPasswordRequest) GetCaID() *string {
	if o == nil {
		return nil
	}
	return o.CaID
}

func (o *GetAPICARotateSCEPPasswordRequest) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

type GetAPICARotateSCEPPasswordResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPICARotateSCEPPasswordResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPICARotateSCEPPasswordResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPICARotateSCEPPasswordResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
