// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type GetAPICAGetCAChainsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TwoHundredTextPlainRes *string
	// OK
	TwoHundredApplicationJSONCAChainInfoModels []shared.CAChainInfoModel
	// OK
	TwoHundredTextJSONCAChainInfoModels []shared.CAChainInfoModel
}

func (o *GetAPICAGetCAChainsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPICAGetCAChainsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPICAGetCAChainsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPICAGetCAChainsResponse) GetTwoHundredTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextPlainRes
}

func (o *GetAPICAGetCAChainsResponse) GetTwoHundredApplicationJSONCAChainInfoModels() []shared.CAChainInfoModel {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONCAChainInfoModels
}

func (o *GetAPICAGetCAChainsResponse) GetTwoHundredTextJSONCAChainInfoModels() []shared.CAChainInfoModel {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextJSONCAChainInfoModels
}
