// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPICAGetCASubordinateCertsRequest struct {
	CaID *string `queryParam:"style=form,explode=true,name=caID"`
}

func (o *GetAPICAGetCASubordinateCertsRequest) GetCaID() *string {
	if o == nil {
		return nil
	}
	return o.CaID
}

type GetAPICAGetCASubordinateCertsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPICAGetCASubordinateCertsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPICAGetCASubordinateCertsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPICAGetCASubordinateCertsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
