// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPICAGetAvailableLocationsRequest struct {
	Premium *bool `queryParam:"style=form,explode=true,name=premium"`
}

func (o *GetAPICAGetAvailableLocationsRequest) GetPremium() *bool {
	if o == nil {
		return nil
	}
	return o.Premium
}

type GetAPICAGetAvailableLocationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TwoHundredTextPlainRes *string
	// OK
	TwoHundredApplicationJSONStrings []string
	// OK
	TwoHundredTextJSONStrings []string
}

func (o *GetAPICAGetAvailableLocationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPICAGetAvailableLocationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPICAGetAvailableLocationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPICAGetAvailableLocationsResponse) GetTwoHundredTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextPlainRes
}

func (o *GetAPICAGetAvailableLocationsResponse) GetTwoHundredApplicationJSONStrings() []string {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONStrings
}

func (o *GetAPICAGetAvailableLocationsResponse) GetTwoHundredTextJSONStrings() []string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextJSONStrings
}
