// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type GetAPIDashboardGetInfoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DashboardModel *string
	// OK
	DashboardModel1 *shared.DashboardModel
}

func (o *GetAPIDashboardGetInfoResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIDashboardGetInfoResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIDashboardGetInfoResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPIDashboardGetInfoResponse) GetDashboardModel() *string {
	if o == nil {
		return nil
	}
	return o.DashboardModel
}

func (o *GetAPIDashboardGetInfoResponse) GetDashboardModel1() *shared.DashboardModel {
	if o == nil {
		return nil
	}
	return o.DashboardModel1
}
