// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type PostAPICAPKIAdminGetDomainDetailsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DomainInformationModel *string
	// OK
	DomainInformationModel1 *shared.DomainInformationModel
}

func (o *PostAPICAPKIAdminGetDomainDetailsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPICAPKIAdminGetDomainDetailsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPICAPKIAdminGetDomainDetailsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostAPICAPKIAdminGetDomainDetailsResponse) GetDomainInformationModel() *string {
	if o == nil {
		return nil
	}
	return o.DomainInformationModel
}

func (o *PostAPICAPKIAdminGetDomainDetailsResponse) GetDomainInformationModel1() *shared.DomainInformationModel {
	if o == nil {
		return nil
	}
	return o.DomainInformationModel1
}
