// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type PostAPIAuditGetCertLogsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TwoHundredTextPlainRes *string
	// OK
	TwoHundredApplicationJSONSSLCertAuditLogModels []shared.SSLCertAuditLogModel
	// OK
	TwoHundredTextJSONSSLCertAuditLogModels []shared.SSLCertAuditLogModel
}

func (o *PostAPIAuditGetCertLogsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPIAuditGetCertLogsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPIAuditGetCertLogsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostAPIAuditGetCertLogsResponse) GetTwoHundredTextPlainRes() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextPlainRes
}

func (o *PostAPIAuditGetCertLogsResponse) GetTwoHundredApplicationJSONSSLCertAuditLogModels() []shared.SSLCertAuditLogModel {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONSSLCertAuditLogModels
}

func (o *PostAPIAuditGetCertLogsResponse) GetTwoHundredTextJSONSSLCertAuditLogModels() []shared.SSLCertAuditLogModel {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextJSONSSLCertAuditLogModels
}
