// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/models/shared"
	"net/http"
)

type PostAPICATestPublicCAConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DomainsResponseModel *string
	// OK
	DomainsResponseModel1 *shared.DomainsResponseModel
}

func (o *PostAPICATestPublicCAConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPICATestPublicCAConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPICATestPublicCAConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostAPICATestPublicCAConnectionResponse) GetDomainsResponseModel() *string {
	if o == nil {
		return nil
	}
	return o.DomainsResponseModel
}

func (o *PostAPICATestPublicCAConnectionResponse) GetDomainsResponseModel1() *shared.DomainsResponseModel {
	if o == nil {
		return nil
	}
	return o.DomainsResponseModel1
}
