// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ADCSCAReqConnecitonModel struct {
	CAName   *string `json:"CAName,omitempty"`
	AgentURL *string `json:"AgentURL,omitempty"`
	CACert   *string `json:"CACert,omitempty"`
}

func (o *ADCSCAReqConnecitonModel) GetCAName() *string {
	if o == nil {
		return nil
	}
	return o.CAName
}

func (o *ADCSCAReqConnecitonModel) GetAgentURL() *string {
	if o == nil {
		return nil
	}
	return o.AgentURL
}

func (o *ADCSCAReqConnecitonModel) GetCACert() *string {
	if o == nil {
		return nil
	}
	return o.CACert
}
