// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ADCSCARequestModel struct {
	SelectedSub       *SubscriptionInformationModel `json:"SelectedSub,omitempty"`
	CAType            *string                       `json:"CAType,omitempty"`
	CAFriendlyName    *string                       `json:"CAFriendlyName,omitempty"`
	CAs               []ADCSCAReqConnecitonModel    `json:"CAs,omitempty"`
	NotificationEmail *string                       `json:"NotificationEmail,omitempty"`
	CATemplates       []CACertTemplateReqModel      `json:"CATemplates,omitempty"`
}

func (o *ADCSCARequestModel) GetSelectedSub() *SubscriptionInformationModel {
	if o == nil {
		return nil
	}
	return o.SelectedSub
}

func (o *ADCSCARequestModel) GetCAType() *string {
	if o == nil {
		return nil
	}
	return o.CAType
}

func (o *ADCSCARequestModel) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}

func (o *ADCSCARequestModel) GetCAs() []ADCSCAReqConnecitonModel {
	if o == nil {
		return nil
	}
	return o.CAs
}

func (o *ADCSCARequestModel) GetNotificationEmail() *string {
	if o == nil {
		return nil
	}
	return o.NotificationEmail
}

func (o *ADCSCARequestModel) GetCATemplates() []CACertTemplateReqModel {
	if o == nil {
		return nil
	}
	return o.CATemplates
}
