// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AgentTestRequestModel struct {
	AgentURL     *string `json:"AgentURL,omitempty"`
	TemplateName *string `json:"TemplateName,omitempty"`
	CAName       *string `json:"CAName,omitempty"`
	AuthCert     *string `json:"AuthCert,omitempty"`
	TestUserName *string `json:"TestUserName,omitempty"`
}

func (o *AgentTestRequestModel) GetAgentURL() *string {
	if o == nil {
		return nil
	}
	return o.AgentURL
}

func (o *AgentTestRequestModel) GetTemplateName() *string {
	if o == nil {
		return nil
	}
	return o.TemplateName
}

func (o *AgentTestRequestModel) GetCAName() *string {
	if o == nil {
		return nil
	}
	return o.CAName
}

func (o *AgentTestRequestModel) GetAuthCert() *string {
	if o == nil {
		return nil
	}
	return o.AuthCert
}

func (o *AgentTestRequestModel) GetTestUserName() *string {
	if o == nil {
		return nil
	}
	return o.TestUserName
}
