// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AKVModel struct {
	VaultLocation  *string `json:"VaultLocation,omitempty"`
	VaultVaultName *string `json:"VaultVaultName,omitempty"`
}

func (o *AKVModel) GetVaultLocation() *string {
	if o == nil {
		return nil
	}
	return o.VaultLocation
}

func (o *AKVModel) GetVaultVaultName() *string {
	if o == nil {
		return nil
	}
	return o.VaultVaultName
}
