// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type AuditRequestModel struct {
	DateFrom *time.Time `json:"DateFrom,omitempty"`
	DateTo   *time.Time `json:"DateTo,omitempty"`
}

func (a AuditRequestModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuditRequestModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AuditRequestModel) GetDateFrom() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateFrom
}

func (o *AuditRequestModel) GetDateTo() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateTo
}
