// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type BasicCertInfoModel struct {
	SubjectName    *string    `json:"SubjectName,omitempty"`
	Certificate    *string    `json:"Certificate,omitempty"`
	ExpirationDate *time.Time `json:"ExpirationDate,omitempty"`
}

func (b BasicCertInfoModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BasicCertInfoModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BasicCertInfoModel) GetSubjectName() *string {
	if o == nil {
		return nil
	}
	return o.SubjectName
}

func (o *BasicCertInfoModel) GetCertificate() *string {
	if o == nil {
		return nil
	}
	return o.Certificate
}

func (o *BasicCertInfoModel) GetExpirationDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpirationDate
}
