// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CACreateRequestModel struct {
	SelectedSub         *SubscriptionInformationModel      `json:"SelectedSub,omitempty"`
	CAType              *string                            `json:"CAType,omitempty"`
	CATier              *string                            `json:"CATier,omitempty"`
	IssuerInformation   *CAIssuerInformationModel          `json:"IssuerInformation,omitempty"`
	CAKeyType           *string                            `json:"CAKeyType,omitempty"`
	CAHashing           *string                            `json:"CAHashing,omitempty"`
	CALifeTime          *int                               `json:"CALifeTime,omitempty"`
	CRLEnabled          *bool                              `json:"CRLEnabled,omitempty"`
	OCSPEnabled         *bool                              `json:"OCSPEnabled,omitempty"`
	OCSPExtraLocations  []string                           `json:"OCSPExtraLocations,omitempty"`
	CAFriendlyName      *string                            `json:"CAFriendlyName,omitempty"`
	NotificationEmail   *string                            `json:"NotificationEmail,omitempty"`
	AutoRenew           *bool                              `json:"AutoRenew,omitempty"`
	AutoRenewPercentage *int                               `json:"AutoRenewPercentage,omitempty"`
	CRLLength           *int                               `json:"CRLLength,omitempty"`
	CRLOverlap          *int                               `json:"CRLOverlap,omitempty"`
	CRLCustomURL        *string                            `json:"CRLCustomURL,omitempty"`
	CATemplates         []CACertTemplateReqModel           `json:"CATemplates,omitempty"`
	CALocation          *string                            `json:"CALocation,omitempty"`
	SecondaryLocations  []SecondaryCALocationsRequestModel `json:"SecondaryLocations,omitempty"`
}

func (o *CACreateRequestModel) GetSelectedSub() *SubscriptionInformationModel {
	if o == nil {
		return nil
	}
	return o.SelectedSub
}

func (o *CACreateRequestModel) GetCAType() *string {
	if o == nil {
		return nil
	}
	return o.CAType
}

func (o *CACreateRequestModel) GetCATier() *string {
	if o == nil {
		return nil
	}
	return o.CATier
}

func (o *CACreateRequestModel) GetIssuerInformation() *CAIssuerInformationModel {
	if o == nil {
		return nil
	}
	return o.IssuerInformation
}

func (o *CACreateRequestModel) GetCAKeyType() *string {
	if o == nil {
		return nil
	}
	return o.CAKeyType
}

func (o *CACreateRequestModel) GetCAHashing() *string {
	if o == nil {
		return nil
	}
	return o.CAHashing
}

func (o *CACreateRequestModel) GetCALifeTime() *int {
	if o == nil {
		return nil
	}
	return o.CALifeTime
}

func (o *CACreateRequestModel) GetCRLEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.CRLEnabled
}

func (o *CACreateRequestModel) GetOCSPEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.OCSPEnabled
}

func (o *CACreateRequestModel) GetOCSPExtraLocations() []string {
	if o == nil {
		return nil
	}
	return o.OCSPExtraLocations
}

func (o *CACreateRequestModel) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}

func (o *CACreateRequestModel) GetNotificationEmail() *string {
	if o == nil {
		return nil
	}
	return o.NotificationEmail
}

func (o *CACreateRequestModel) GetAutoRenew() *bool {
	if o == nil {
		return nil
	}
	return o.AutoRenew
}

func (o *CACreateRequestModel) GetAutoRenewPercentage() *int {
	if o == nil {
		return nil
	}
	return o.AutoRenewPercentage
}

func (o *CACreateRequestModel) GetCRLLength() *int {
	if o == nil {
		return nil
	}
	return o.CRLLength
}

func (o *CACreateRequestModel) GetCRLOverlap() *int {
	if o == nil {
		return nil
	}
	return o.CRLOverlap
}

func (o *CACreateRequestModel) GetCRLCustomURL() *string {
	if o == nil {
		return nil
	}
	return o.CRLCustomURL
}

func (o *CACreateRequestModel) GetCATemplates() []CACertTemplateReqModel {
	if o == nil {
		return nil
	}
	return o.CATemplates
}

func (o *CACreateRequestModel) GetCALocation() *string {
	if o == nil {
		return nil
	}
	return o.CALocation
}

func (o *CACreateRequestModel) GetSecondaryLocations() []SecondaryCALocationsRequestModel {
	if o == nil {
		return nil
	}
	return o.SecondaryLocations
}
