// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CADetailInformationModel struct {
	Caid                *string               `json:"CAID,omitempty"`
	Subid               *string               `json:"SUBID,omitempty"`
	CAKeyType           *string               `json:"CAKeyType,omitempty"`
	CAHashing           *string               `json:"CAHashing,omitempty"`
	CAType              *string               `json:"CAType,omitempty"`
	CATier              *string               `json:"CATier,omitempty"`
	CAFriendlyName      *string               `json:"CAFriendlyName,omitempty"`
	CALifeTime          *int                  `json:"CALifeTime,omitempty"`
	NotificationEmail   *string               `json:"NotificationEmail,omitempty"`
	AutoRenew           *bool                 `json:"AutoRenew,omitempty"`
	AutoRenewPercentage *int                  `json:"AutoRenewPercentage,omitempty"`
	LocalCAs            []LocalCADetailsModel `json:"LocalCAs,omitempty"`
}

func (o *CADetailInformationModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *CADetailInformationModel) GetSubid() *string {
	if o == nil {
		return nil
	}
	return o.Subid
}

func (o *CADetailInformationModel) GetCAKeyType() *string {
	if o == nil {
		return nil
	}
	return o.CAKeyType
}

func (o *CADetailInformationModel) GetCAHashing() *string {
	if o == nil {
		return nil
	}
	return o.CAHashing
}

func (o *CADetailInformationModel) GetCAType() *string {
	if o == nil {
		return nil
	}
	return o.CAType
}

func (o *CADetailInformationModel) GetCATier() *string {
	if o == nil {
		return nil
	}
	return o.CATier
}

func (o *CADetailInformationModel) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}

func (o *CADetailInformationModel) GetCALifeTime() *int {
	if o == nil {
		return nil
	}
	return o.CALifeTime
}

func (o *CADetailInformationModel) GetNotificationEmail() *string {
	if o == nil {
		return nil
	}
	return o.NotificationEmail
}

func (o *CADetailInformationModel) GetAutoRenew() *bool {
	if o == nil {
		return nil
	}
	return o.AutoRenew
}

func (o *CADetailInformationModel) GetAutoRenewPercentage() *int {
	if o == nil {
		return nil
	}
	return o.AutoRenewPercentage
}

func (o *CADetailInformationModel) GetLocalCAs() []LocalCADetailsModel {
	if o == nil {
		return nil
	}
	return o.LocalCAs
}
