// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CAInformationModel struct {
	Caid           *string `json:"CAID,omitempty"`
	Subid          *string `json:"SUBID,omitempty"`
	CAKeyType      *string `json:"CAKeyType,omitempty"`
	CAHashing      *string `json:"CAHashing,omitempty"`
	CATier         *string `json:"CATier,omitempty"`
	CAFriendlyName *string `json:"CAFriendlyName,omitempty"`
	CommonName     *string `json:"CommonName,omitempty"`
	CALocation     *string `json:"CALocation,omitempty"`
}

func (o *CAInformationModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *CAInformationModel) GetSubid() *string {
	if o == nil {
		return nil
	}
	return o.Subid
}

func (o *CAInformationModel) GetCAKeyType() *string {
	if o == nil {
		return nil
	}
	return o.CAKeyType
}

func (o *CAInformationModel) GetCAHashing() *string {
	if o == nil {
		return nil
	}
	return o.CAHashing
}

func (o *CAInformationModel) GetCATier() *string {
	if o == nil {
		return nil
	}
	return o.CATier
}

func (o *CAInformationModel) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}

func (o *CAInformationModel) GetCommonName() *string {
	if o == nil {
		return nil
	}
	return o.CommonName
}

func (o *CAInformationModel) GetCALocation() *string {
	if o == nil {
		return nil
	}
	return o.CALocation
}
