// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CAIntegrationRequestModel struct {
	Caid              *string `json:"CAID,omitempty"`
	Subid             *string `json:"SUBID,omitempty"`
	ResourceID        *string `json:"ResourceID,omitempty"`
	DisableIoTDevices *bool   `json:"DisableIoTDevices,omitempty"`
}

func (o *CAIntegrationRequestModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *CAIntegrationRequestModel) GetSubid() *string {
	if o == nil {
		return nil
	}
	return o.Subid
}

func (o *CAIntegrationRequestModel) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}

func (o *CAIntegrationRequestModel) GetDisableIoTDevices() *bool {
	if o == nil {
		return nil
	}
	return o.DisableIoTDevices
}
