// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CAShortInformationModel struct {
	Caid           *string `json:"CAID,omitempty"`
	CAFriendlyName *string `json:"CAFriendlyName,omitempty"`
}

func (o *CAShortInformationModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *CAShortInformationModel) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}
