// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CertificateCreateRequestV2Model struct {
	SubjectName         *string           `json:"SubjectName,omitempty"`
	SubjectAltNames     []SubjectAltValue `json:"SubjectAltNames,omitempty"`
	Caid                *string           `json:"CAID,omitempty"`
	TemplateID          *string           `json:"TemplateID,omitempty"`
	Csr                 *string           `json:"CSR,omitempty"`
	ValidityInDays      *int              `json:"ValidityInDays,omitempty"`
	EKUs                []string          `json:"EKUs,omitempty"`
	KeyUsages           []string          `json:"KeyUsages,omitempty"`
	SelectedLocation    *string           `json:"SelectedLocation,omitempty"`
	ResourceID          *string           `json:"ResourceID,omitempty"`
	SecretName          *string           `json:"SecretName,omitempty"`
	AKVName             *string           `json:"AKVName,omitempty"`
	AutoRenew           *bool             `json:"AutoRenew,omitempty"`
	AutoRenewPercentage *int              `json:"AutoRenewPercentage,omitempty"`
	CertAppID           *string           `json:"CertAppID,omitempty"`
	CertificateTags     *string           `json:"CertificateTags,omitempty"`
	Sid                 *string           `json:"SID,omitempty"`
}

func (o *CertificateCreateRequestV2Model) GetSubjectName() *string {
	if o == nil {
		return nil
	}
	return o.SubjectName
}

func (o *CertificateCreateRequestV2Model) GetSubjectAltNames() []SubjectAltValue {
	if o == nil {
		return nil
	}
	return o.SubjectAltNames
}

func (o *CertificateCreateRequestV2Model) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *CertificateCreateRequestV2Model) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *CertificateCreateRequestV2Model) GetCsr() *string {
	if o == nil {
		return nil
	}
	return o.Csr
}

func (o *CertificateCreateRequestV2Model) GetValidityInDays() *int {
	if o == nil {
		return nil
	}
	return o.ValidityInDays
}

func (o *CertificateCreateRequestV2Model) GetEKUs() []string {
	if o == nil {
		return nil
	}
	return o.EKUs
}

func (o *CertificateCreateRequestV2Model) GetKeyUsages() []string {
	if o == nil {
		return nil
	}
	return o.KeyUsages
}

func (o *CertificateCreateRequestV2Model) GetSelectedLocation() *string {
	if o == nil {
		return nil
	}
	return o.SelectedLocation
}

func (o *CertificateCreateRequestV2Model) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}

func (o *CertificateCreateRequestV2Model) GetSecretName() *string {
	if o == nil {
		return nil
	}
	return o.SecretName
}

func (o *CertificateCreateRequestV2Model) GetAKVName() *string {
	if o == nil {
		return nil
	}
	return o.AKVName
}

func (o *CertificateCreateRequestV2Model) GetAutoRenew() *bool {
	if o == nil {
		return nil
	}
	return o.AutoRenew
}

func (o *CertificateCreateRequestV2Model) GetAutoRenewPercentage() *int {
	if o == nil {
		return nil
	}
	return o.AutoRenewPercentage
}

func (o *CertificateCreateRequestV2Model) GetCertAppID() *string {
	if o == nil {
		return nil
	}
	return o.CertAppID
}

func (o *CertificateCreateRequestV2Model) GetCertificateTags() *string {
	if o == nil {
		return nil
	}
	return o.CertificateTags
}

func (o *CertificateCreateRequestV2Model) GetSid() *string {
	if o == nil {
		return nil
	}
	return o.Sid
}
