// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type CertAuditRequestModel struct {
	DateFrom    *time.Time `json:"DateFrom,omitempty"`
	DateTo      *time.Time `json:"DateTo,omitempty"`
	TenantID    *string    `json:"TenantID,omitempty"`
	Caid        *string    `json:"CAID,omitempty"`
	Certificate *string    `json:"Certificate,omitempty"`
}

func (c CertAuditRequestModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CertAuditRequestModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CertAuditRequestModel) GetDateFrom() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateFrom
}

func (o *CertAuditRequestModel) GetDateTo() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateTo
}

func (o *CertAuditRequestModel) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *CertAuditRequestModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *CertAuditRequestModel) GetCertificate() *string {
	if o == nil {
		return nil
	}
	return o.Certificate
}
