// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DashboardChartModel struct {
	Data   []float64 `json:"Data,omitempty"`
	Labels []string  `json:"Labels,omitempty"`
}

func (o *DashboardChartModel) GetData() []float64 {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *DashboardChartModel) GetLabels() []string {
	if o == nil {
		return nil
	}
	return o.Labels
}
