// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DashboardModel struct {
	ActiveCerts         *int                 `json:"ActiveCerts,omitempty"`
	RevokedCerts        *int                 `json:"RevokedCerts,omitempty"`
	RegisteredDomains   *int                 `json:"RegisteredDomains,omitempty"`
	CertsExpiring15Days *int                 `json:"CertsExpiring15Days,omitempty"`
	CAByStatus          *DashboardChartModel `json:"CAByStatus,omitempty"`
	CAByKeyType         *DashboardChartModel `json:"CAByKeyType,omitempty"`
	CertsByCreation     *DashboardChartModel `json:"CertsByCreation,omitempty"`
	CertAutoRenew       *DashboardChartModel `json:"CertAutoRenew,omitempty"`
}

func (o *DashboardModel) GetActiveCerts() *int {
	if o == nil {
		return nil
	}
	return o.ActiveCerts
}

func (o *DashboardModel) GetRevokedCerts() *int {
	if o == nil {
		return nil
	}
	return o.RevokedCerts
}

func (o *DashboardModel) GetRegisteredDomains() *int {
	if o == nil {
		return nil
	}
	return o.RegisteredDomains
}

func (o *DashboardModel) GetCertsExpiring15Days() *int {
	if o == nil {
		return nil
	}
	return o.CertsExpiring15Days
}

func (o *DashboardModel) GetCAByStatus() *DashboardChartModel {
	if o == nil {
		return nil
	}
	return o.CAByStatus
}

func (o *DashboardModel) GetCAByKeyType() *DashboardChartModel {
	if o == nil {
		return nil
	}
	return o.CAByKeyType
}

func (o *DashboardModel) GetCertsByCreation() *DashboardChartModel {
	if o == nil {
		return nil
	}
	return o.CertsByCreation
}

func (o *DashboardModel) GetCertAutoRenew() *DashboardChartModel {
	if o == nil {
		return nil
	}
	return o.CertAutoRenew
}
