// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DBACMEAgentModel struct {
	TenantID        *string `json:"TenantID,omitempty"`
	Subid           *string `json:"SUBID,omitempty"`
	Caid            *string `json:"CAID,omitempty"`
	CertSubjectName *string `json:"CertSubjectName,omitempty"`
	Name            *string `json:"Name,omitempty"`
	URL             *string `json:"URL,omitempty"`
	TestHealth      *bool   `json:"TestHealth,omitempty"`
}

func (o *DBACMEAgentModel) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DBACMEAgentModel) GetSubid() *string {
	if o == nil {
		return nil
	}
	return o.Subid
}

func (o *DBACMEAgentModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *DBACMEAgentModel) GetCertSubjectName() *string {
	if o == nil {
		return nil
	}
	return o.CertSubjectName
}

func (o *DBACMEAgentModel) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *DBACMEAgentModel) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *DBACMEAgentModel) GetTestHealth() *bool {
	if o == nil {
		return nil
	}
	return o.TestHealth
}
