// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type DBCAIntegrationModel struct {
	TenantID                  *string    `json:"TenantID,omitempty"`
	Caid                      *string    `json:"CAID,omitempty"`
	IntegrationType           *string    `json:"IntegrationType,omitempty"`
	IntegrationEndpoint       *string    `json:"IntegrationEndpoint,omitempty"`
	IntegrationEndpointParent *string    `json:"IntegrationEndpointParent,omitempty"`
	WorkersAdded              *string    `json:"WorkersAdded,omitempty"`
	CertNames                 *string    `json:"CertNames,omitempty"`
	CertTags                  *string    `json:"CertTags,omitempty"`
	CreateDate                *time.Time `json:"CreateDate,omitempty"`
	Requester                 *string    `json:"Requester,omitempty"`
	RevokeIoTDevices          *bool      `json:"RevokeIoTDevices,omitempty"`
}

func (d DBCAIntegrationModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DBCAIntegrationModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DBCAIntegrationModel) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DBCAIntegrationModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *DBCAIntegrationModel) GetIntegrationType() *string {
	if o == nil {
		return nil
	}
	return o.IntegrationType
}

func (o *DBCAIntegrationModel) GetIntegrationEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.IntegrationEndpoint
}

func (o *DBCAIntegrationModel) GetIntegrationEndpointParent() *string {
	if o == nil {
		return nil
	}
	return o.IntegrationEndpointParent
}

func (o *DBCAIntegrationModel) GetWorkersAdded() *string {
	if o == nil {
		return nil
	}
	return o.WorkersAdded
}

func (o *DBCAIntegrationModel) GetCertNames() *string {
	if o == nil {
		return nil
	}
	return o.CertNames
}

func (o *DBCAIntegrationModel) GetCertTags() *string {
	if o == nil {
		return nil
	}
	return o.CertTags
}

func (o *DBCAIntegrationModel) GetCreateDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreateDate
}

func (o *DBCAIntegrationModel) GetRequester() *string {
	if o == nil {
		return nil
	}
	return o.Requester
}

func (o *DBCAIntegrationModel) GetRevokeIoTDevices() *bool {
	if o == nil {
		return nil
	}
	return o.RevokeIoTDevices
}
