// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type DBDomainRegistrationReqModel struct {
	TenantID             *string    `json:"TenantID,omitempty"`
	Caid                 *string    `json:"CAID,omitempty"`
	TemplateID           *string    `json:"TemplateID,omitempty"`
	Domain               *string    `json:"Domain,omitempty"`
	DateRequested        *time.Time `json:"DateRequested,omitempty"`
	OriginalRegistration *string    `json:"OriginalRegistration,omitempty"`
	NewRegistration      *string    `json:"NewRegistration,omitempty"`
	Action               *string    `json:"Action,omitempty"`
	RequesterID          *string    `json:"RequesterID,omitempty"`
	RequesterUPN         *string    `json:"RequesterUPN,omitempty"`
	DateApproved         *time.Time `json:"DateApproved,omitempty"`
	Approver             *string    `json:"Approver,omitempty"`
	CAFriendlyName       *string    `json:"CAFriendlyName,omitempty"`
	Approved             *bool      `json:"Approved,omitempty"`
}

func (d DBDomainRegistrationReqModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DBDomainRegistrationReqModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DBDomainRegistrationReqModel) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DBDomainRegistrationReqModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *DBDomainRegistrationReqModel) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *DBDomainRegistrationReqModel) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *DBDomainRegistrationReqModel) GetDateRequested() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateRequested
}

func (o *DBDomainRegistrationReqModel) GetOriginalRegistration() *string {
	if o == nil {
		return nil
	}
	return o.OriginalRegistration
}

func (o *DBDomainRegistrationReqModel) GetNewRegistration() *string {
	if o == nil {
		return nil
	}
	return o.NewRegistration
}

func (o *DBDomainRegistrationReqModel) GetAction() *string {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *DBDomainRegistrationReqModel) GetRequesterID() *string {
	if o == nil {
		return nil
	}
	return o.RequesterID
}

func (o *DBDomainRegistrationReqModel) GetRequesterUPN() *string {
	if o == nil {
		return nil
	}
	return o.RequesterUPN
}

func (o *DBDomainRegistrationReqModel) GetDateApproved() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateApproved
}

func (o *DBDomainRegistrationReqModel) GetApprover() *string {
	if o == nil {
		return nil
	}
	return o.Approver
}

func (o *DBDomainRegistrationReqModel) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}

func (o *DBDomainRegistrationReqModel) GetApproved() *bool {
	if o == nil {
		return nil
	}
	return o.Approved
}
