// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type DBSelfServiceCertificate struct {
	TenantID            *string    `json:"TenantID,omitempty"`
	UserID              *string    `json:"UserID,omitempty"`
	Thumbprint          *string    `json:"Thumbprint,omitempty"`
	CaID                *string    `json:"CaID,omitempty"`
	CATenantID          *string    `json:"CATenantID,omitempty"`
	TemplateID          *string    `json:"TemplateID,omitempty"`
	ProfileID           *string    `json:"ProfileID,omitempty"`
	CertificatePEM      *string    `json:"CertificatePEM,omitempty"`
	CertificateFriendly *string    `json:"CertificateFriendly,omitempty"`
	PrivateKeyPEM       *string    `json:"PrivateKeyPEM,omitempty"`
	Csr                 *string    `json:"CSR,omitempty"`
	UserUPN             *string    `json:"UserUPN,omitempty"`
	ExpirationDate      *time.Time `json:"ExpirationDate,omitempty"`
	PolicyName          *string    `json:"PolicyName,omitempty"`
}

func (d DBSelfServiceCertificate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DBSelfServiceCertificate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DBSelfServiceCertificate) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DBSelfServiceCertificate) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *DBSelfServiceCertificate) GetThumbprint() *string {
	if o == nil {
		return nil
	}
	return o.Thumbprint
}

func (o *DBSelfServiceCertificate) GetCaID() *string {
	if o == nil {
		return nil
	}
	return o.CaID
}

func (o *DBSelfServiceCertificate) GetCATenantID() *string {
	if o == nil {
		return nil
	}
	return o.CATenantID
}

func (o *DBSelfServiceCertificate) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *DBSelfServiceCertificate) GetProfileID() *string {
	if o == nil {
		return nil
	}
	return o.ProfileID
}

func (o *DBSelfServiceCertificate) GetCertificatePEM() *string {
	if o == nil {
		return nil
	}
	return o.CertificatePEM
}

func (o *DBSelfServiceCertificate) GetCertificateFriendly() *string {
	if o == nil {
		return nil
	}
	return o.CertificateFriendly
}

func (o *DBSelfServiceCertificate) GetPrivateKeyPEM() *string {
	if o == nil {
		return nil
	}
	return o.PrivateKeyPEM
}

func (o *DBSelfServiceCertificate) GetCsr() *string {
	if o == nil {
		return nil
	}
	return o.Csr
}

func (o *DBSelfServiceCertificate) GetUserUPN() *string {
	if o == nil {
		return nil
	}
	return o.UserUPN
}

func (o *DBSelfServiceCertificate) GetExpirationDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpirationDate
}

func (o *DBSelfServiceCertificate) GetPolicyName() *string {
	if o == nil {
		return nil
	}
	return o.PolicyName
}
