// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DBSelfServiceGuest struct {
	TenantID   *string `json:"TenantID,omitempty"`
	CaTenantID *string `json:"CaTenantID,omitempty"`
	CaID       *string `json:"CaID,omitempty"`
	TemplateID *string `json:"TemplateID,omitempty"`
	ProfileID  *string `json:"ProfileID,omitempty"`
	AllUsers   *bool   `json:"allUsers,omitempty"`
	PolicyName *string `json:"PolicyName,omitempty"`
}

func (o *DBSelfServiceGuest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DBSelfServiceGuest) GetCaTenantID() *string {
	if o == nil {
		return nil
	}
	return o.CaTenantID
}

func (o *DBSelfServiceGuest) GetCaID() *string {
	if o == nil {
		return nil
	}
	return o.CaID
}

func (o *DBSelfServiceGuest) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *DBSelfServiceGuest) GetProfileID() *string {
	if o == nil {
		return nil
	}
	return o.ProfileID
}

func (o *DBSelfServiceGuest) GetAllUsers() *bool {
	if o == nil {
		return nil
	}
	return o.AllUsers
}

func (o *DBSelfServiceGuest) GetPolicyName() *string {
	if o == nil {
		return nil
	}
	return o.PolicyName
}
