// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DBSelfServiceAcls struct {
	TenantID       *string `json:"TenantID,omitempty"`
	CaID           *string `json:"CaID,omitempty"`
	TemplateID     *string `json:"TemplateID,omitempty"`
	ProfileID      *string `json:"ProfileID,omitempty"`
	ObjectID       *string `json:"ObjectID,omitempty"`
	ObjectType     *string `json:"objectType,omitempty"`
	ObjectName     *string `json:"objectName,omitempty"`
	ObjectTenantID *string `json:"ObjectTenantID,omitempty"`
}

func (o *DBSelfServiceAcls) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DBSelfServiceAcls) GetCaID() *string {
	if o == nil {
		return nil
	}
	return o.CaID
}

func (o *DBSelfServiceAcls) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *DBSelfServiceAcls) GetProfileID() *string {
	if o == nil {
		return nil
	}
	return o.ProfileID
}

func (o *DBSelfServiceAcls) GetObjectID() *string {
	if o == nil {
		return nil
	}
	return o.ObjectID
}

func (o *DBSelfServiceAcls) GetObjectType() *string {
	if o == nil {
		return nil
	}
	return o.ObjectType
}

func (o *DBSelfServiceAcls) GetObjectName() *string {
	if o == nil {
		return nil
	}
	return o.ObjectName
}

func (o *DBSelfServiceAcls) GetObjectTenantID() *string {
	if o == nil {
		return nil
	}
	return o.ObjectTenantID
}
