// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DomainsResponseModel struct {
	Success      *bool                  `json:"Success,omitempty"`
	ErrorMessage *string                `json:"ErrorMessage,omitempty"`
	Domains      []PublicDomainResponse `json:"Domains,omitempty"`
}

func (o *DomainsResponseModel) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *DomainsResponseModel) GetErrorMessage() *string {
	if o == nil {
		return nil
	}
	return o.ErrorMessage
}

func (o *DomainsResponseModel) GetDomains() []PublicDomainResponse {
	if o == nil {
		return nil
	}
	return o.Domains
}
