// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DomainInformationModel struct {
	Caid               *string          `json:"CAID,omitempty"`
	TemplateID         *string          `json:"TemplateID,omitempty"`
	DomainID           *string          `json:"DomainID,omitempty"`
	Domain             *string          `json:"Domain,omitempty"`
	CAFriendlyName     *string          `json:"CAFriendlyName,omitempty"`
	IsOwner            *bool            `json:"IsOwner,omitempty"`
	IsRequester        *bool            `json:"IsRequester,omitempty"`
	Owners             []AADObjectModel `json:"Owners,omitempty"`
	Requesters         []AADObjectModel `json:"Requesters,omitempty"`
	RequestersOnly     []AADObjectModel `json:"RequestersOnly,omitempty"`
	NotificationEmails []string         `json:"NotificationEmails,omitempty"`
}

func (o *DomainInformationModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *DomainInformationModel) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *DomainInformationModel) GetDomainID() *string {
	if o == nil {
		return nil
	}
	return o.DomainID
}

func (o *DomainInformationModel) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *DomainInformationModel) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}

func (o *DomainInformationModel) GetIsOwner() *bool {
	if o == nil {
		return nil
	}
	return o.IsOwner
}

func (o *DomainInformationModel) GetIsRequester() *bool {
	if o == nil {
		return nil
	}
	return o.IsRequester
}

func (o *DomainInformationModel) GetOwners() []AADObjectModel {
	if o == nil {
		return nil
	}
	return o.Owners
}

func (o *DomainInformationModel) GetRequesters() []AADObjectModel {
	if o == nil {
		return nil
	}
	return o.Requesters
}

func (o *DomainInformationModel) GetRequestersOnly() []AADObjectModel {
	if o == nil {
		return nil
	}
	return o.RequestersOnly
}

func (o *DomainInformationModel) GetNotificationEmails() []string {
	if o == nil {
		return nil
	}
	return o.NotificationEmails
}
