// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EKUModel struct {
	Oid          *string `json:"Oid,omitempty"`
	FriendlyName *string `json:"FriendlyName,omitempty"`
	Selected     *bool   `json:"Selected,omitempty"`
}

func (o *EKUModel) GetOid() *string {
	if o == nil {
		return nil
	}
	return o.Oid
}

func (o *EKUModel) GetFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.FriendlyName
}

func (o *EKUModel) GetSelected() *bool {
	if o == nil {
		return nil
	}
	return o.Selected
}
