// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ExternalCASigningReq struct {
	Caid           *string `json:"CAID,omitempty"`
	Csr            *string `json:"CSR,omitempty"`
	FriendlyName   *string `json:"FriendlyName,omitempty"`
	LengthInMonths *int    `json:"LengthInMonths,omitempty"`
	CheckForCAFlag *bool   `json:"CheckForCAFlag,omitempty"`
}

func (o *ExternalCASigningReq) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *ExternalCASigningReq) GetCsr() *string {
	if o == nil {
		return nil
	}
	return o.Csr
}

func (o *ExternalCASigningReq) GetFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.FriendlyName
}

func (o *ExternalCASigningReq) GetLengthInMonths() *int {
	if o == nil {
		return nil
	}
	return o.LengthInMonths
}

func (o *ExternalCASigningReq) GetCheckForCAFlag() *bool {
	if o == nil {
		return nil
	}
	return o.CheckForCAFlag
}
