// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type F5AgentRequest struct {
	AgentName              *string                   `json:"AgentName,omitempty"`
	CertificateSubjectName *string                   `json:"CertificateSubjectName,omitempty"`
	RequestingCertCA       *CAShortInformationModel  `json:"RequestingCertCA,omitempty"`
	Tags                   *string                   `json:"Tags,omitempty"`
	NotificationEmails     *string                   `json:"NotificationEmails,omitempty"`
	Owners                 []AADObjectModel          `json:"Owners,omitempty"`
	AllowedCAs             []CAShortInformationModel `json:"AllowedCAs,omitempty"`
	F5Devices              []F5RequestModel          `json:"F5Devices,omitempty"`
}

func (o *F5AgentRequest) GetAgentName() *string {
	if o == nil {
		return nil
	}
	return o.AgentName
}

func (o *F5AgentRequest) GetCertificateSubjectName() *string {
	if o == nil {
		return nil
	}
	return o.CertificateSubjectName
}

func (o *F5AgentRequest) GetRequestingCertCA() *CAShortInformationModel {
	if o == nil {
		return nil
	}
	return o.RequestingCertCA
}

func (o *F5AgentRequest) GetTags() *string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *F5AgentRequest) GetNotificationEmails() *string {
	if o == nil {
		return nil
	}
	return o.NotificationEmails
}

func (o *F5AgentRequest) GetOwners() []AADObjectModel {
	if o == nil {
		return nil
	}
	return o.Owners
}

func (o *F5AgentRequest) GetAllowedCAs() []CAShortInformationModel {
	if o == nil {
		return nil
	}
	return o.AllowedCAs
}

func (o *F5AgentRequest) GetF5Devices() []F5RequestModel {
	if o == nil {
		return nil
	}
	return o.F5Devices
}
