// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GuestSelfServiceCertRequest struct {
	SelfServiceProfile  *SelfServiceGuestDetails `json:"SelfServiceProfile,omitempty"`
	Csr                 *string                  `json:"CSR,omitempty"`
	PrivateKey          *string                  `json:"PrivateKey,omitempty"`
	CertificateName     *string                  `json:"CertificateName,omitempty"`
	SaveCertInEZCA      *bool                    `json:"SaveCertInEZCA,omitempty"`
	AutoRotate          *bool                    `json:"AutoRotate,omitempty"`
	AutoRotateThreshold *int                     `json:"AutoRotateThreshold,omitempty"`
}

func (o *GuestSelfServiceCertRequest) GetSelfServiceProfile() *SelfServiceGuestDetails {
	if o == nil {
		return nil
	}
	return o.SelfServiceProfile
}

func (o *GuestSelfServiceCertRequest) GetCsr() *string {
	if o == nil {
		return nil
	}
	return o.Csr
}

func (o *GuestSelfServiceCertRequest) GetPrivateKey() *string {
	if o == nil {
		return nil
	}
	return o.PrivateKey
}

func (o *GuestSelfServiceCertRequest) GetCertificateName() *string {
	if o == nil {
		return nil
	}
	return o.CertificateName
}

func (o *GuestSelfServiceCertRequest) GetSaveCertInEZCA() *bool {
	if o == nil {
		return nil
	}
	return o.SaveCertInEZCA
}

func (o *GuestSelfServiceCertRequest) GetAutoRotate() *bool {
	if o == nil {
		return nil
	}
	return o.AutoRotate
}

func (o *GuestSelfServiceCertRequest) GetAutoRotateThreshold() *int {
	if o == nil {
		return nil
	}
	return o.AutoRotateThreshold
}
