// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type IntermediateCertRequestModel struct {
	CAResponse    *CACreatedResponseModel `json:"CAResponse,omitempty"`
	CAInformation *CAInformationModel     `json:"CAInformation,omitempty"`
}

func (o *IntermediateCertRequestModel) GetCAResponse() *CACreatedResponseModel {
	if o == nil {
		return nil
	}
	return o.CAResponse
}

func (o *IntermediateCertRequestModel) GetCAInformation() *CAInformationModel {
	if o == nil {
		return nil
	}
	return o.CAInformation
}
