// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type LocalCADetailsModel struct {
	TenantID         *string    `json:"TenantID,omitempty"`
	Caid             *string    `json:"CAID,omitempty"`
	SubID            *string    `json:"SubID,omitempty"`
	CALocation       *string    `json:"CALocation,omitempty"`
	CAKeyType        *string    `json:"CAKeyType,omitempty"`
	CAHashing        *string    `json:"CAHashing,omitempty"`
	Organization     *string    `json:"Organization,omitempty"`
	OrganizationUnit *string    `json:"OrganizationUnit,omitempty"`
	CommonName       *string    `json:"CommonName,omitempty"`
	CountryCode      *string    `json:"CountryCode,omitempty"`
	Status           *string    `json:"Status,omitempty"`
	CACertificate    *string    `json:"CACertificate,omitempty"`
	Csr              *string    `json:"CSR,omitempty"`
	ParentCert       *string    `json:"ParentCert,omitempty"`
	AgentURL         *string    `json:"AgentURL,omitempty"`
	CloudProvider    *string    `json:"CloudProvider,omitempty"`
	ExpiryDate       *time.Time `json:"ExpiryDate,omitempty"`
	CRLRealLocation  *string    `json:"CRLRealLocation,omitempty"`
	CRLFriendlyURL   *string    `json:"CRLFriendlyURL,omitempty"`
	CertFriendlyURL  *string    `json:"CertFriendlyURL,omitempty"`
	WorkerID         *string    `json:"WorkerID,omitempty"`
}

func (l LocalCADetailsModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LocalCADetailsModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *LocalCADetailsModel) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *LocalCADetailsModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *LocalCADetailsModel) GetSubID() *string {
	if o == nil {
		return nil
	}
	return o.SubID
}

func (o *LocalCADetailsModel) GetCALocation() *string {
	if o == nil {
		return nil
	}
	return o.CALocation
}

func (o *LocalCADetailsModel) GetCAKeyType() *string {
	if o == nil {
		return nil
	}
	return o.CAKeyType
}

func (o *LocalCADetailsModel) GetCAHashing() *string {
	if o == nil {
		return nil
	}
	return o.CAHashing
}

func (o *LocalCADetailsModel) GetOrganization() *string {
	if o == nil {
		return nil
	}
	return o.Organization
}

func (o *LocalCADetailsModel) GetOrganizationUnit() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationUnit
}

func (o *LocalCADetailsModel) GetCommonName() *string {
	if o == nil {
		return nil
	}
	return o.CommonName
}

func (o *LocalCADetailsModel) GetCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.CountryCode
}

func (o *LocalCADetailsModel) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *LocalCADetailsModel) GetCACertificate() *string {
	if o == nil {
		return nil
	}
	return o.CACertificate
}

func (o *LocalCADetailsModel) GetCsr() *string {
	if o == nil {
		return nil
	}
	return o.Csr
}

func (o *LocalCADetailsModel) GetParentCert() *string {
	if o == nil {
		return nil
	}
	return o.ParentCert
}

func (o *LocalCADetailsModel) GetAgentURL() *string {
	if o == nil {
		return nil
	}
	return o.AgentURL
}

func (o *LocalCADetailsModel) GetCloudProvider() *string {
	if o == nil {
		return nil
	}
	return o.CloudProvider
}

func (o *LocalCADetailsModel) GetExpiryDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiryDate
}

func (o *LocalCADetailsModel) GetCRLRealLocation() *string {
	if o == nil {
		return nil
	}
	return o.CRLRealLocation
}

func (o *LocalCADetailsModel) GetCRLFriendlyURL() *string {
	if o == nil {
		return nil
	}
	return o.CRLFriendlyURL
}

func (o *LocalCADetailsModel) GetCertFriendlyURL() *string {
	if o == nil {
		return nil
	}
	return o.CertFriendlyURL
}

func (o *LocalCADetailsModel) GetWorkerID() *string {
	if o == nil {
		return nil
	}
	return o.WorkerID
}
