// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type LocalCACreatedResponseModel struct {
	Csr        *string `json:"CSR,omitempty"`
	Cert       *string `json:"Cert,omitempty"`
	ParentCert *string `json:"ParentCert,omitempty"`
	Status     *string `json:"Status,omitempty"`
	Location   *string `json:"Location,omitempty"`
	CommonName *string `json:"CommonName,omitempty"`
}

func (o *LocalCACreatedResponseModel) GetCsr() *string {
	if o == nil {
		return nil
	}
	return o.Csr
}

func (o *LocalCACreatedResponseModel) GetCert() *string {
	if o == nil {
		return nil
	}
	return o.Cert
}

func (o *LocalCACreatedResponseModel) GetParentCert() *string {
	if o == nil {
		return nil
	}
	return o.ParentCert
}

func (o *LocalCACreatedResponseModel) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *LocalCACreatedResponseModel) GetLocation() *string {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *LocalCACreatedResponseModel) GetCommonName() *string {
	if o == nil {
		return nil
	}
	return o.CommonName
}
