// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NewDomainRegistrationRequest struct {
	Caid               *string          `json:"CAID,omitempty"`
	TemplateID         *string          `json:"TemplateID,omitempty"`
	Domain             *string          `json:"Domain,omitempty"`
	Owners             []AADObjectModel `json:"Owners,omitempty"`
	Requesters         []AADObjectModel `json:"Requesters,omitempty"`
	RequestersOnly     []AADObjectModel `json:"RequestersOnly,omitempty"`
	NotificationEmails []string         `json:"NotificationEmails,omitempty"`
}

func (o *NewDomainRegistrationRequest) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *NewDomainRegistrationRequest) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *NewDomainRegistrationRequest) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *NewDomainRegistrationRequest) GetOwners() []AADObjectModel {
	if o == nil {
		return nil
	}
	return o.Owners
}

func (o *NewDomainRegistrationRequest) GetRequesters() []AADObjectModel {
	if o == nil {
		return nil
	}
	return o.Requesters
}

func (o *NewDomainRegistrationRequest) GetRequestersOnly() []AADObjectModel {
	if o == nil {
		return nil
	}
	return o.RequestersOnly
}

func (o *NewDomainRegistrationRequest) GetNotificationEmails() []string {
	if o == nil {
		return nil
	}
	return o.NotificationEmails
}
