// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PublicCACredentials struct {
	SubID              *string `json:"SubID,omitempty"`
	Caid               *string `json:"CAID,omitempty"`
	CAProvider         *string `json:"CAProvider,omitempty"`
	CAProviderUserName *string `json:"CAProviderUserName,omitempty"`
	CAProviderPassword *string `json:"CAProviderPassword,omitempty"`
	CAProfileID        *string `json:"CAProfileID,omitempty"`
}

func (o *PublicCACredentials) GetSubID() *string {
	if o == nil {
		return nil
	}
	return o.SubID
}

func (o *PublicCACredentials) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *PublicCACredentials) GetCAProvider() *string {
	if o == nil {
		return nil
	}
	return o.CAProvider
}

func (o *PublicCACredentials) GetCAProviderUserName() *string {
	if o == nil {
		return nil
	}
	return o.CAProviderUserName
}

func (o *PublicCACredentials) GetCAProviderPassword() *string {
	if o == nil {
		return nil
	}
	return o.CAProviderPassword
}

func (o *PublicCACredentials) GetCAProfileID() *string {
	if o == nil {
		return nil
	}
	return o.CAProfileID
}
