// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type PublicDomainResponse struct {
	DomainID             *string    `json:"DomainID,omitempty"`
	DomainName           *string    `json:"DomainName,omitempty"`
	Validated            *bool      `json:"Validated,omitempty"`
	ValidationMethod     *string    `json:"ValidationMethod,omitempty"`
	ValidationLevel      *string    `json:"ValidationLevel,omitempty"`
	ValidationDateExpiry *time.Time `json:"ValidationDateExpiry,omitempty"`
	AllowWildCards       *bool      `json:"AllowWildCards,omitempty"`
	AllowACME            *bool      `json:"AllowACME,omitempty"`
}

func (p PublicDomainResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicDomainResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PublicDomainResponse) GetDomainID() *string {
	if o == nil {
		return nil
	}
	return o.DomainID
}

func (o *PublicDomainResponse) GetDomainName() *string {
	if o == nil {
		return nil
	}
	return o.DomainName
}

func (o *PublicDomainResponse) GetValidated() *bool {
	if o == nil {
		return nil
	}
	return o.Validated
}

func (o *PublicDomainResponse) GetValidationMethod() *string {
	if o == nil {
		return nil
	}
	return o.ValidationMethod
}

func (o *PublicDomainResponse) GetValidationLevel() *string {
	if o == nil {
		return nil
	}
	return o.ValidationLevel
}

func (o *PublicDomainResponse) GetValidationDateExpiry() *time.Time {
	if o == nil {
		return nil
	}
	return o.ValidationDateExpiry
}

func (o *PublicDomainResponse) GetAllowWildCards() *bool {
	if o == nil {
		return nil
	}
	return o.AllowWildCards
}

func (o *PublicDomainResponse) GetAllowACME() *bool {
	if o == nil {
		return nil
	}
	return o.AllowACME
}
