// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PublicCARequest struct {
	SelectedSub        *SubscriptionInformationModel `json:"SelectedSub,omitempty"`
	CAProvider         *string                       `json:"CAProvider,omitempty"`
	CAProviderUserName *string                       `json:"CAProviderUserName,omitempty"`
	CAProfileID        *string                       `json:"CAProfileID,omitempty"`
	CAProviderPassword *string                       `json:"CAProviderPassword,omitempty"`
	NotificationEmail  *string                       `json:"NotificationEmail,omitempty"`
	CATemplate         *PublicCATemplateRequestModel `json:"CATemplate,omitempty"`
}

func (o *PublicCARequest) GetSelectedSub() *SubscriptionInformationModel {
	if o == nil {
		return nil
	}
	return o.SelectedSub
}

func (o *PublicCARequest) GetCAProvider() *string {
	if o == nil {
		return nil
	}
	return o.CAProvider
}

func (o *PublicCARequest) GetCAProviderUserName() *string {
	if o == nil {
		return nil
	}
	return o.CAProviderUserName
}

func (o *PublicCARequest) GetCAProfileID() *string {
	if o == nil {
		return nil
	}
	return o.CAProfileID
}

func (o *PublicCARequest) GetCAProviderPassword() *string {
	if o == nil {
		return nil
	}
	return o.CAProviderPassword
}

func (o *PublicCARequest) GetNotificationEmail() *string {
	if o == nil {
		return nil
	}
	return o.NotificationEmail
}

func (o *PublicCARequest) GetCATemplate() *PublicCATemplateRequestModel {
	if o == nil {
		return nil
	}
	return o.CATemplate
}
