// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SecondaryCALocationsRequestModel struct {
	CALocation  *string `json:"CALocation,omitempty"`
	CAName      *string `json:"CAName,omitempty"`
	CountryCode *string `json:"CountryCode,omitempty"`
}

func (o *SecondaryCALocationsRequestModel) GetCALocation() *string {
	if o == nil {
		return nil
	}
	return o.CALocation
}

func (o *SecondaryCALocationsRequestModel) GetCAName() *string {
	if o == nil {
		return nil
	}
	return o.CAName
}

func (o *SecondaryCALocationsRequestModel) GetCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.CountryCode
}
