// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SelfServiceProfileModel struct {
	SelfServiceProfile *DBSelfServiceScep          `json:"SelfServiceProfile,omitempty"`
	GuestProfiles      []SelfServiceGuestModel     `json:"GuestProfiles,omitempty"`
	Acls               []DBSelfServiceAcls         `json:"Acls,omitempty"`
	Sans               []SubjectAlternateNameModel `json:"Sans,omitempty"`
	EKUs               []EKUModel                  `json:"EKUs,omitempty"`
	KeyUsages          []APIResultModel            `json:"KeyUsages,omitempty"`
}

func (o *SelfServiceProfileModel) GetSelfServiceProfile() *DBSelfServiceScep {
	if o == nil {
		return nil
	}
	return o.SelfServiceProfile
}

func (o *SelfServiceProfileModel) GetGuestProfiles() []SelfServiceGuestModel {
	if o == nil {
		return nil
	}
	return o.GuestProfiles
}

func (o *SelfServiceProfileModel) GetAcls() []DBSelfServiceAcls {
	if o == nil {
		return nil
	}
	return o.Acls
}

func (o *SelfServiceProfileModel) GetSans() []SubjectAlternateNameModel {
	if o == nil {
		return nil
	}
	return o.Sans
}

func (o *SelfServiceProfileModel) GetEKUs() []EKUModel {
	if o == nil {
		return nil
	}
	return o.EKUs
}

func (o *SelfServiceProfileModel) GetKeyUsages() []APIResultModel {
	if o == nil {
		return nil
	}
	return o.KeyUsages
}
