// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SelfServiceGuestModel struct {
	GuestProfile *DBSelfServiceGuest `json:"GuestProfile,omitempty"`
	Acls         []DBSelfServiceAcls `json:"Acls,omitempty"`
}

func (o *SelfServiceGuestModel) GetGuestProfile() *DBSelfServiceGuest {
	if o == nil {
		return nil
	}
	return o.GuestProfile
}

func (o *SelfServiceGuestModel) GetAcls() []DBSelfServiceAcls {
	if o == nil {
		return nil
	}
	return o.Acls
}
