// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SelfServiceGuestDetails struct {
	OriginalTenantPolicy *DBSelfServiceScep  `json:"OriginalTenantPolicy,omitempty"`
	GuestPolicy          *DBSelfServiceGuest `json:"GuestPolicy,omitempty"`
}

func (o *SelfServiceGuestDetails) GetOriginalTenantPolicy() *DBSelfServiceScep {
	if o == nil {
		return nil
	}
	return o.OriginalTenantPolicy
}

func (o *SelfServiceGuestDetails) GetGuestPolicy() *DBSelfServiceGuest {
	if o == nil {
		return nil
	}
	return o.GuestPolicy
}
