// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SelfServiceCertRequest struct {
	SelfServiceProfile  *DBSelfServiceScep `json:"SelfServiceProfile,omitempty"`
	Csr                 *string            `json:"CSR,omitempty"`
	PrivateKey          *string            `json:"PrivateKey,omitempty"`
	CertificateName     *string            `json:"CertificateName,omitempty"`
	SaveCertInEZCA      *bool              `json:"SaveCertInEZCA,omitempty"`
	AutoRotate          *bool              `json:"AutoRotate,omitempty"`
	AutoRotateThreshold *int               `json:"AutoRotateThreshold,omitempty"`
}

func (o *SelfServiceCertRequest) GetSelfServiceProfile() *DBSelfServiceScep {
	if o == nil {
		return nil
	}
	return o.SelfServiceProfile
}

func (o *SelfServiceCertRequest) GetCsr() *string {
	if o == nil {
		return nil
	}
	return o.Csr
}

func (o *SelfServiceCertRequest) GetPrivateKey() *string {
	if o == nil {
		return nil
	}
	return o.PrivateKey
}

func (o *SelfServiceCertRequest) GetCertificateName() *string {
	if o == nil {
		return nil
	}
	return o.CertificateName
}

func (o *SelfServiceCertRequest) GetSaveCertInEZCA() *bool {
	if o == nil {
		return nil
	}
	return o.SaveCertInEZCA
}

func (o *SelfServiceCertRequest) GetAutoRotate() *bool {
	if o == nil {
		return nil
	}
	return o.AutoRotate
}

func (o *SelfServiceCertRequest) GetAutoRotateThreshold() *int {
	if o == nil {
		return nil
	}
	return o.AutoRotateThreshold
}
