// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type SSLCertAuditLogModel struct {
	TenantID           *string    `json:"TenantID,omitempty"`
	Caid               *string    `json:"CAID,omitempty"`
	DateRequested      *time.Time `json:"DateRequested,omitempty"`
	Domain             *string    `json:"Domain,omitempty"`
	Thumbprint         *string    `json:"Thumbprint,omitempty"`
	TemplateID         *string    `json:"TemplateID,omitempty"`
	CertificatePEM     *string    `json:"CertificatePEM,omitempty"`
	SubID              *string    `json:"SubID,omitempty"`
	Requester          *string    `json:"Requester,omitempty"`
	CAFriendlyName     *string    `json:"CAFriendlyName,omitempty"`
	CertLocationType   *string    `json:"CertLocationType,omitempty"`
	CertLocation       *string    `json:"CertLocation,omitempty"`
	CertNameAtLocation *string    `json:"CertNameAtLocation,omitempty"`
	Action             *string    `json:"Action,omitempty"`
}

func (s SSLCertAuditLogModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSLCertAuditLogModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SSLCertAuditLogModel) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *SSLCertAuditLogModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *SSLCertAuditLogModel) GetDateRequested() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateRequested
}

func (o *SSLCertAuditLogModel) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *SSLCertAuditLogModel) GetThumbprint() *string {
	if o == nil {
		return nil
	}
	return o.Thumbprint
}

func (o *SSLCertAuditLogModel) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *SSLCertAuditLogModel) GetCertificatePEM() *string {
	if o == nil {
		return nil
	}
	return o.CertificatePEM
}

func (o *SSLCertAuditLogModel) GetSubID() *string {
	if o == nil {
		return nil
	}
	return o.SubID
}

func (o *SSLCertAuditLogModel) GetRequester() *string {
	if o == nil {
		return nil
	}
	return o.Requester
}

func (o *SSLCertAuditLogModel) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}

func (o *SSLCertAuditLogModel) GetCertLocationType() *string {
	if o == nil {
		return nil
	}
	return o.CertLocationType
}

func (o *SSLCertAuditLogModel) GetCertLocation() *string {
	if o == nil {
		return nil
	}
	return o.CertLocation
}

func (o *SSLCertAuditLogModel) GetCertNameAtLocation() *string {
	if o == nil {
		return nil
	}
	return o.CertNameAtLocation
}

func (o *SSLCertAuditLogModel) GetAction() *string {
	if o == nil {
		return nil
	}
	return o.Action
}
