// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type SSLCertInfo struct {
	CertificatePEM        *string    `json:"CertificatePEM,omitempty"`
	Thumbprint            *string    `json:"Thumbprint,omitempty"`
	Caid                  *string    `json:"CAID,omitempty"`
	SubjectName           *string    `json:"SubjectName,omitempty"`
	TemplateID            *string    `json:"TemplateID,omitempty"`
	Revoked               *bool      `json:"Revoked,omitempty"`
	SubjectAlternateNames []string   `json:"SubjectAlternateNames,omitempty"`
	KeyUsages             []string   `json:"KeyUsages,omitempty"`
	EKUs                  []string   `json:"EKUs,omitempty"`
	DateRequested         *time.Time `json:"DateRequested,omitempty"`
	ExpiryDate            *time.Time `json:"ExpiryDate,omitempty"`
	CertLocationType      *string    `json:"CertLocationType,omitempty"`
	CertLocation          *string    `json:"CertLocation,omitempty"`
	CAFriendlyName        *string    `json:"CAFriendlyName,omitempty"`
	CertNameAtLocation    *string    `json:"CertNameAtLocation,omitempty"`
	AutoRenew             *bool      `json:"AutoRenew,omitempty"`
	AutoRenewPercentage   *int       `json:"AutoRenewPercentage,omitempty"`
	CertLengthDays        *int       `json:"CertLengthDays,omitempty"`
	CertAppID             *string    `json:"CertAppID,omitempty"`
	CertificateTags       *string    `json:"CertificateTags,omitempty"`
	CanRevoke             *bool      `json:"CanRevoke,omitempty"`
}

func (s SSLCertInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSLCertInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SSLCertInfo) GetCertificatePEM() *string {
	if o == nil {
		return nil
	}
	return o.CertificatePEM
}

func (o *SSLCertInfo) GetThumbprint() *string {
	if o == nil {
		return nil
	}
	return o.Thumbprint
}

func (o *SSLCertInfo) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *SSLCertInfo) GetSubjectName() *string {
	if o == nil {
		return nil
	}
	return o.SubjectName
}

func (o *SSLCertInfo) GetTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *SSLCertInfo) GetRevoked() *bool {
	if o == nil {
		return nil
	}
	return o.Revoked
}

func (o *SSLCertInfo) GetSubjectAlternateNames() []string {
	if o == nil {
		return nil
	}
	return o.SubjectAlternateNames
}

func (o *SSLCertInfo) GetKeyUsages() []string {
	if o == nil {
		return nil
	}
	return o.KeyUsages
}

func (o *SSLCertInfo) GetEKUs() []string {
	if o == nil {
		return nil
	}
	return o.EKUs
}

func (o *SSLCertInfo) GetDateRequested() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateRequested
}

func (o *SSLCertInfo) GetExpiryDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiryDate
}

func (o *SSLCertInfo) GetCertLocationType() *string {
	if o == nil {
		return nil
	}
	return o.CertLocationType
}

func (o *SSLCertInfo) GetCertLocation() *string {
	if o == nil {
		return nil
	}
	return o.CertLocation
}

func (o *SSLCertInfo) GetCAFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.CAFriendlyName
}

func (o *SSLCertInfo) GetCertNameAtLocation() *string {
	if o == nil {
		return nil
	}
	return o.CertNameAtLocation
}

func (o *SSLCertInfo) GetAutoRenew() *bool {
	if o == nil {
		return nil
	}
	return o.AutoRenew
}

func (o *SSLCertInfo) GetAutoRenewPercentage() *int {
	if o == nil {
		return nil
	}
	return o.AutoRenewPercentage
}

func (o *SSLCertInfo) GetCertLengthDays() *int {
	if o == nil {
		return nil
	}
	return o.CertLengthDays
}

func (o *SSLCertInfo) GetCertAppID() *string {
	if o == nil {
		return nil
	}
	return o.CertAppID
}

func (o *SSLCertInfo) GetCertificateTags() *string {
	if o == nil {
		return nil
	}
	return o.CertificateTags
}

func (o *SSLCertInfo) GetCanRevoke() *bool {
	if o == nil {
		return nil
	}
	return o.CanRevoke
}
