// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/thomasgeens/terraform-provider-ezca/internal/sdk/internal/utils"
	"time"
)

type SubCADetailsModel struct {
	ParentCAID    *string    `json:"ParentCAID,omitempty"`
	FriendlyName  *string    `json:"FriendlyName,omitempty"`
	SubjectName   *string    `json:"SubjectName,omitempty"`
	ExpiryDate    *time.Time `json:"ExpiryDate,omitempty"`
	CACertificate *string    `json:"CACertificate,omitempty"`
	Caid          *string    `json:"CAID,omitempty"`
	IsRevoked     *bool      `json:"IsRevoked,omitempty"`
	IsExternalCA  *bool      `json:"IsExternalCA,omitempty"`
	WorkerID      *string    `json:"WorkerID,omitempty"`
	CALocation    *string    `json:"CALocation,omitempty"`
	Status        *string    `json:"Status,omitempty"`
}

func (s SubCADetailsModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubCADetailsModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SubCADetailsModel) GetParentCAID() *string {
	if o == nil {
		return nil
	}
	return o.ParentCAID
}

func (o *SubCADetailsModel) GetFriendlyName() *string {
	if o == nil {
		return nil
	}
	return o.FriendlyName
}

func (o *SubCADetailsModel) GetSubjectName() *string {
	if o == nil {
		return nil
	}
	return o.SubjectName
}

func (o *SubCADetailsModel) GetExpiryDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiryDate
}

func (o *SubCADetailsModel) GetCACertificate() *string {
	if o == nil {
		return nil
	}
	return o.CACertificate
}

func (o *SubCADetailsModel) GetCaid() *string {
	if o == nil {
		return nil
	}
	return o.Caid
}

func (o *SubCADetailsModel) GetIsRevoked() *bool {
	if o == nil {
		return nil
	}
	return o.IsRevoked
}

func (o *SubCADetailsModel) GetIsExternalCA() *bool {
	if o == nil {
		return nil
	}
	return o.IsExternalCA
}

func (o *SubCADetailsModel) GetWorkerID() *string {
	if o == nil {
		return nil
	}
	return o.WorkerID
}

func (o *SubCADetailsModel) GetCALocation() *string {
	if o == nil {
		return nil
	}
	return o.CALocation
}

func (o *SubCADetailsModel) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}
