// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SubjectAlternateNameModel struct {
	SanType  *string `json:"SanType,omitempty"`
	SanValue *string `json:"SanValue,omitempty"`
}

func (o *SubjectAlternateNameModel) GetSanType() *string {
	if o == nil {
		return nil
	}
	return o.SanType
}

func (o *SubjectAlternateNameModel) GetSanValue() *string {
	if o == nil {
		return nil
	}
	return o.SanValue
}
