// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SubjectAltValue struct {
	ValueSTR       *string `json:"ValueSTR,omitempty"`
	SubjectAltType *int    `json:"SubjectAltType,omitempty"`
}

func (o *SubjectAltValue) GetValueSTR() *string {
	if o == nil {
		return nil
	}
	return o.ValueSTR
}

func (o *SubjectAltValue) GetSubjectAltType() *int {
	if o == nil {
		return nil
	}
	return o.SubjectAltType
}
